serviceAccount: projects/meanrevcontact/serviceAccounts/877026809152-compute@developer.gserviceaccount.com
options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

steps:
  # Build Backend
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "asia-south1-docker.pkg.dev/meanrevcontact/meanrevrepo/backend:$SHORT_SHA",
        "./backend"
      ]

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "asia-south1-docker.pkg.dev/meanrevcontact/meanrevrepo/backend:$SHORT_SHA"
      ]

  # Build Frontend
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "asia-south1-docker.pkg.dev/meanrevcontact/meanrevrepo/frontend:$SHORT_SHA",
        "./frontend"
      ]

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "asia-south1-docker.pkg.dev/meanrevcontact/meanrevrepo/frontend:$SHORT_SHA"
      ]

  # SSH → Update Compose → Pull → Restart Services
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - -c
      - |
        gcloud compute ssh meanrev-app-server --zone="asia-south1-b" --command "
          cd /var/www/app &&
          sed -i \"s/latest/$SHORT_SHA/g\" compose.yml &&
          docker compose pull &&
          docker compose down &&
          docker compose up -d
        "

images:
  - "asia-south1-docker.pkg.dev/meanrevcontact/meanrevrepo/backend:$SHORT_SHA"
  - "asia-south1-docker.pkg.dev/meanrevcontact/meanrevrepo/frontend:$SHORT_SHA"

timeout: "1800s"
